{
 "title": "IoT Bridge / Services / Azure IoT Hub",
 "tags": [ "tartabit-iot-bridge" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "accountId",
    "label": "Account",
    "query": {
     "query": "query_result(max by (accountId, accountName) (iotbridge_account_map))"
    }
   },
   {
    "name": "serviceId",
    "label": "Service",
    "query": {
     "query": "query_result(max by (accountId, serviceId, serviceName) (iotbridge_service_map{accountId=~\"${accountId:regex}\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(iotbridge_azure_iot_connections{accountId=~\"${accountId:regex}\", serviceId=~\"${serviceId:regex}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "connections per pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(iotbridge_azure_iot_connections{accountId=~\"${accountId:regex}\", serviceId=~\"${serviceId:regex}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "connections per account",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,sum by (accountId)(iotbridge_azure_iot_connections{accountId=~\"${accountId:regex}\", serviceId=~\"${serviceId:regex}\"})) * on(accountId) group_left(accountName) max by (accountId, accountName) (iotbridge_account_map)",
     "legendFormat": "{{accountName}}"
    }
   ]
  },
  {
   "title": "connection time per pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(increase(iotbridge_azure_iot_connect_time_sum{serviceId=~\"${serviceId:regex}\"}[1m]))/sum by (pod)(increase(iotbridge_azure_iot_connect_time_count{serviceId=~\"${serviceId:regex}\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "go routines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"svc-azure-iot-.+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ops/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(iotbridge_trigger_action_exectime_count{pod=~\"svc-azure-iot-.+\", accountId=~\"${accountId:regex}\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "ops/sec by pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(iotbridge_trigger_action_exectime_count{pod=~\"svc-azure-iot-.+\", accountId=~\"${accountId:regex}\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "action executions/sec per account",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (accountId) (rate(iotbridge_trigger_action_exectime_count{pod=~\"svc-azure-iot-.+\", accountId=~\"${accountId:regex}\"}[$__rate_interval]))) * on(accountId) group_left(accountName) max by (accountId, accountName) (iotbridge_account_map)",
     "legendFormat": "{{accountName}}"
    }
   ]
  },
  {
   "title": "ops/sec by type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type)(rate(iotbridge_trigger_action_exectime_count{pod=~\"svc-azure-iot-.+\", accountId=~\"${accountId:regex}\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(20,avg by (namespace,pod)(container_memory_working_set_bytes{namespace!=\"kube-system\", container!=\"POD\", pod=~\"svc-azure-iot-.+\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "connections per configured service",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum by (accountId, serviceId) (iotbridge_azure_iot_connections{accountId=~\"${accountId:regex}\", serviceId=~\"${serviceId:regex}\"}) * on(accountId,serviceId) group_left(accountName,serviceName) max by (accountId, serviceId, accountName, serviceName) (iotbridge_service_map{accountId=~\"${accountId:regex}\", serviceId=~\"${serviceId:regex}\"})",
     "legendFormat": "{{accountName}} / {{serviceName}}"
    }
   ]
  },
  { "title": "Internal Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "ops/sec per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (pod)(rate(iotbridge_trigger_action_exectime_count{pod=~\"svc-azure-iot-.+\", accountId=~\"${accountId:regex}\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "global lock time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(iotbridge_azure_iot_lock_time_sum{serviceId=~\"${serviceId:regex}\"}[$__rate_interval])>0"
    }
   ]
  },
  {
   "title": "create attempts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (pod,method,result)(rate(iotbridge_azure_iot_create_time_count{serviceId=~\"${serviceId:regex}\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "create time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_azure_iot_create_time_bucket{serviceId=~\"${serviceId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "device mutex hold time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(iotbridge_azure_iot_device_mux_hold_time_sum[$__rate_interval])>0"
    }
   ]
  },
  {
   "title": "connection attempts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (pod,result)(rate(iotbridge_azure_iot_connect_time_count{serviceId=~\"${serviceId:regex}\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "connection time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_azure_iot_connect_time_bucket{serviceId=~\"${serviceId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "device mutex wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(iotbridge_azure_iot_device_mux_wait_time_sum[$__rate_interval])>0"
    }
   ]
  },
  {
   "title": "reconnects/min per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(iotbridge_azure_iot_reconnects{accountId=~\"${accountId:regex}\"}[$__rate_interval])) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "failed connection attempts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 32 },
   "targets": [
    {
     "expr": "sum by (pod,result)(rate(iotbridge_azure_iot_connect_time_count{result=~\"^failed.+\", serviceId=~\"${serviceId:regex}\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Action execution times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "send exec time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_trigger_action_exectime_bucket{type=\"azure-iot-send\", accountId=~\"${accountId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "twin update exec time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_trigger_action_exectime_bucket{type=\"azure-iot-twin-update\", accountId=~\"${accountId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "device update exec time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_trigger_action_exectime_bucket{type=\"azure-iot-device-update\", accountId=~\"${accountId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "direct method complete exec time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_trigger_action_exectime_bucket{type=\"azure-iot-direct-method-complete\", accountId=~\"${accountId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "twin get exec time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_trigger_action_exectime_bucket{type=\"azure-iot-twin-get\", accountId=~\"${accountId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "device get exec time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_trigger_action_exectime_bucket{type=\"azure-iot-device-get\", accountId=~\"${accountId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "twin retrieve exec time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_trigger_action_exectime_bucket{type=\"azure-iot-twin-retrieve\", accountId=~\"${accountId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}