{
 "title": "IoT Bridge / Triggers / Action Performance",
 "tags": [ "tartabit-iot-bridge" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "accountId",
    "label": "Account",
    "query": {
     "query": "query_result(max by (accountId, accountName) (iotbridge_account_map))"
    }
   },
   {
    "name": "service",
    "label": "Runtime service",
    "query": {
     "query": "label_values(iotbridge_trigger_action_exectime_count{accountId=~\"${accountId:regex}\"},container)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(iotbridge_trigger_action_exectime_count{accountId=~\"${accountId:regex}\", container=~\"${service:regex}\"},type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Action exec/min by runtime service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container)(increase(iotbridge_trigger_action_exectime_count{container=~\"${service:regex}\", accountId=~\"${accountId:regex}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Action exec/min by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type)(increase(iotbridge_trigger_action_exectime_count{container=~\"${service:regex}\", type=~\"${type:regex}\", accountId=~\"${accountId:regex}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Delivery Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (container,type)(avg_over_time(iotbridge_trigger_action_delay{container=~\"${service:regex}\", type=~\"${type:regex}\"}[$__interval]))",
     "legendFormat": "{{container}}/{{type}}"
    }
   ]
  },
  {
   "title": "trigger execution time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_trigger_action_exectime_bucket{container=~\"${service:regex}\", type=~\"${type:regex}\", accountId=~\"${accountId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Actions received per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (container)(increase(iotbridge_trigger_action_receive{container=~\"${service:regex}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}