{
 "title": "IoT Bridge / System / Redis",
 "tags": [ "tartabit-iot-bridge" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "ops / sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(redis_commands_total[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "connected clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(redis_connected_clients)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(redis_memory_used_bytes)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "last bgsave",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_rdb_last_save_timestamp_seconds*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "slave replication delay",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_slave_lag_seconds",
     "legendFormat": "{{slave_ip}}"
    }
   ]
  },
  {
   "title": "redis commands per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "rate(redis_commands_total[1m])", "legendFormat": "{{pod}}/{{cmd}}" }
   ]
  },
  {
   "title": "redis keys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "avg(redis_db_keys{db=\"db0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connected clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (pod)(redis_connected_clients)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "average exec time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(redis_commands_duration_seconds_total[1m])/rate(redis_commands_total[1m])",
     "legendFormat": "{{pod}}/{{cmd}}"
    }
   ]
  }
 ]
}