{
 "title": "IoT Bridge / Services / Azure Service Bus",
 "tags": [ "tartabit-iot-bridge" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "Account",
    "query": {
     "query": "query_result(max by (accountId, accountName) (iotbridge_account_map))"
    }
   },
   {
    "name": "serviceId",
    "label": "Service",
    "query": {
     "query": "query_result(max by (accountId, serviceId, serviceName) (iotbridge_service_map{accountId=~\"${account:regex}\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ops/min per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod,type)(rate(iotbridge_trigger_action_exectime_count{pod=~\"svc-azure-servicebus-.+\", accountId=~\"${account:regex}\"}[$__rate_interval])) * 60",
     "legendFormat": "{{pod}}/{{type}}"
    }
   ]
  },
  {
   "title": "go routines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"svc-azure-servicebus-.+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(20,avg by (namespace,pod)(container_memory_working_set_bytes{namespace!=\"kube-system\", container!=\"POD\", pod=~\"svc-azure-servicebus-.+\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ops/min per account",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (accountId,type)(rate(iotbridge_trigger_action_exectime_count{pod=~\"svc-azure-servicebus-.+\", accountId=~\"${account:regex}\"}[$__rate_interval])) * 60 * on(accountId) group_left(accountName) max by (accountId, accountName) (iotbridge_account_map)>0",
     "legendFormat": "{{accountName}}/{{type}}"
    }
   ]
  },
  {
   "title": "messages received/min by service",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (accountId, serviceId) (rate(iotbridge_azure_servicebus_processing_time_count{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"}[$__rate_interval])) * 60 * on(accountId,serviceId) group_left(accountName,serviceName) max by (accountId, serviceId, accountName, serviceName) (iotbridge_service_map{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"})",
     "legendFormat": "{{accountName}} / {{serviceName}}"
    }
   ]
  },
  {
   "title": "average send time by service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by (accountId, serviceId) (rate(iotbridge_azure_servicebus_send_time_sum{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"}[$__rate_interval])) / sum by (accountId, serviceId) (rate(iotbridge_azure_servicebus_send_time_count{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"}[$__rate_interval]))) * on(accountId,serviceId) group_left(accountName,serviceName) max by (accountId, serviceId, accountName, serviceName) (iotbridge_service_map{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"})",
     "legendFormat": "{{accountName}} / {{serviceName}}"
    }
   ]
  },
  {
   "title": "average processing time by service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by (accountId, serviceId) (rate(iotbridge_azure_servicebus_processing_time_sum{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"}[$__rate_interval])) / sum by (accountId, serviceId) (rate(iotbridge_azure_servicebus_processing_time_count{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"}[$__rate_interval]))) * on(accountId,serviceId) group_left(accountName,serviceName) max by (accountId, serviceId, accountName, serviceName) (iotbridge_service_map{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"})",
     "legendFormat": "{{accountName}} / {{serviceName}}"
    }
   ]
  },
  {
   "title": "messages sent/min by service",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (accountId, serviceId) (rate(iotbridge_azure_servicebus_send_time_count{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"}[$__rate_interval])) * 60 * on(accountId,serviceId) group_left(accountName,serviceName) max by (accountId, serviceId, accountName, serviceName) (iotbridge_service_map{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"})",
     "legendFormat": "{{accountName}} / {{serviceName}}"
    }
   ]
  },
  {
   "title": "global send time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_azure_servicebus_send_time_bucket{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "global processing time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(iotbridge_azure_servicebus_processing_time_bucket{accountId=~\"${account:regex}\", serviceId=~\"${serviceId:regex}\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Internal Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } }
 ]
}