{
 "title": "IoT Bridge / Services / LWM2M",
 "tags": [ "tartabit-iot-bridge" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "accountId",
    "label": "Account",
    "query": {
     "query": "query_result(max by (accountId, accountName) (iotbridge_account_map))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "LWM2M operations/min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(iotbridge_lwm2m_operations{accountId=~\"${accountId:regex}\"}[1m]))",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "lwm2m sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(iotbridge_lwm2m_sessions{accountId=~\"${accountId:regex}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ops/min per pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(increase(iotbridge_lwm2m_operations{accountId=~\"${accountId:regex}\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "sessions per pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(iotbridge_lwm2m_sessions{accountId=~\"${accountId:regex}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "operations/min by type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (op)(increase(iotbridge_lwm2m_operations{accountId=~\"${accountId:regex}\"}[1m]))",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "lwm2m operations per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (pod,op)(increase(iotbridge_lwm2m_operations{accountId=~\"${accountId:regex}\"}[1m]))",
     "legendFormat": "{{pod}}/{{op}}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(20,avg by (namespace,pod)(container_memory_working_set_bytes{namespace!=\"kube-system\", container!=\"POD\", pod=~\"svc-lwm2m-.+\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "sum without(instance)(go_goroutines{container=\"svc-lwm2m\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "lwm2m sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum without (accountId,instance)(iotbridge_lwm2m_sessions{accountId=~\"${accountId:regex}\"})",
     "legendFormat": "{{pod}}/{{mode}}"
    }
   ]
  },
  {
   "title": "lwm2m registration time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (le)(rate(iotbridge_lwm2m_op_exec_time_bucket{op=\"registration_time\"}[5m]))>0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "lwm2m update time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (le)(rate(iotbridge_lwm2m_op_exec_time_bucket{op=\"update_time\"}[5m]))>0",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}