{
 "title": "IoT Bridge / Overview",
 "tags": [ "tartabit-iot-bridge" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "cpu usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(0-avg by (instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])), \"internal_ip\", \"$1\", \"instance\", \"(.*):.*\") + on(internal_ip) group_left(node) kube_node_info{}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace((0-node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes), \"internal_ip\", \"$1\", \"instance\", \"(.*):.*\") + on(internal_ip) group_left(node) kube_node_info{}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "volume capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1-sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace!=\"kube-system\"}/kubelet_volume_stats_capacity_bytes{namespace!=\"kube-system\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "node cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-avg by (instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace!=\"kube-system\"}/kubelet_volume_stats_capacity_bytes{namespace!=\"kube-system\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "pods approaching cpu limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod,container)(rate(container_cpu_usage_seconds_total{namespace!=\"kube-system\", container!=\"POD\", container=~\".+\"}[1m]))/avg by (namespace,pod,container)(container_spec_cpu_quota{namespace!=\"kube-system\", container!=\"POD\", container=~\".+\"})>0.1",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "pods approaching memory limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(avg by (namespace,pod,container)(container_memory_working_set_bytes{namespace!=\"kube-system\", container!=\"POD\", container=~\".+\"}))/avg by (namespace,pod,container)(kube_pod_container_resource_limits{namespace!=\"kube-system\", resource=\"memory\"})>.5",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "pod crashes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(increase(kube_pod_container_status_restarts_total{namespace!=\"kube-system\", pod!~\".*-operator-.*\"}[$__range]))>0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cpu throttled pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{namespace!=\"kube-system\", container_name!=\"POD\", image!=\"\"}[15m])>0",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "top 20 pods by memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(20,avg by (namespace,pod)(container_memory_working_set_bytes{namespace!=\"kube-system\", container!=\"POD\", pod=~\".+\"}))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "pod crashes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace)(increase(kube_pod_container_status_restarts_total{namespace!=\"kube-system\", pod!~\".*operator.*\"}[30m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance,job)(go_goroutines{namespace!=\"kube-system\",namespace!=\"monitoring\",pod=~\".+\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "open tcp connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}