{
 "title": "IoT Bridge / System / Redis Streams",
 "tags": [ "tartabit-iot-bridge" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "stream data size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(iotbridge_stream_bytes)" }
   ]
  },
  {
   "title": "stream record count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(iotbridge_stream_length)" }
   ]
  },
  {
   "title": "slow consumers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iotbridge_stream_consumer_delta>0",
     "legendFormat": "{{stream}}/{{consumer}}"
    }
   ]
  },
  {
   "title": "stream memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10,avg without (instance,pod)(iotbridge_stream_bytes))",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "top 10 stream memory consumption",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,avg without (instance,pod)(iotbridge_stream_bytes))",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "stream memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10,avg without (instance,pod)(rate(iotbridge_stream_bytes[1m])))>0",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "stream max age",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (pod,instance)(iotbridge_stream_first_entry{})",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "stream memory consumption",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (stream)(iotbridge_stream_bytes/iotbridge_stream_length)<1000000000",
     "legendFormat": "{{stream}}"
    }
   ]
  }
 ]
}