{
 "title": "IoT Bridge / System / MongoDB",
 "tags": [ "tartabit-iot-bridge" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "total ops/sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(mongodb_top_total_count[2m]))"
    }
   ]
  },
  {
   "title": "insert ops/sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(mongodb_top_insert_count[2m]))"
    }
   ]
  },
  {
   "title": "update ops/sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(mongodb_top_update_count[2m]))"
    }
   ]
  },
  {
   "title": "queries ops/sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(mongodb_top_queries_count[2m]))"
    }
   ]
  },
  {
   "title": "insert time (us)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(mongodb_top_insert_time[2m]))"
    }
   ]
  },
  {
   "title": "update time (us)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(mongodb_top_update_time[2m]))"
    }
   ]
  },
  {
   "title": "query time (us)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(mongodb_top_queries_time[2m]))"
    }
   ]
  },
  {
   "title": "db capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mongodb_dbstats_fsUsedSize{database=\"tartabit\"})/avg(mongodb_dbstats_fsTotalSize{database=\"tartabit\"})"
    }
   ]
  },
  {
   "title": "db size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mongodb_dbstats_dataSize{database=\"tartabit\"})"
    }
   ]
  },
  {
   "title": "time since last election",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_members_electionDate)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "operations per member",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (pod)(rate(mongodb_top_total_count[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  {
   "title": "reads on primary vs secondary",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "sum by (rs_state)(rate(mongodb_top_queries_count[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  {
   "title": "reads on primary by collection",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "sum by (collection)(rate(mongodb_top_queries_count{rs_state=\"1\"}[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "insert rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (collection)(rate(mongodb_top_insert_count{database=\"tartabit\"}[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  {
   "title": "insert execution time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (collection)(rate(mongodb_top_insert_time{database=\"tartabit\"}[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  {
   "title": "update rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (collection)(rate(mongodb_top_update_count{database=\"tartabit\"}[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  {
   "title": "update execution time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (collection)(rate(mongodb_top_update_time{database=\"tartabit\"}[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  {
   "title": "query rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (collection)(rate(mongodb_top_queries_count{database=\"tartabit\"}[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  {
   "title": "query execution time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (collection)(rate(mongodb_top_queries_time{database=\"tartabit\"}[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  {
   "title": "getmore rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (collection)(rate(mongodb_top_getmore_count{database=\"tartabit\"}[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  {
   "title": "getmore execution time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (collection)(rate(mongodb_top_getmore_time{database=\"tartabit\"}[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  {
   "title": "remove rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (collection)(rate(mongodb_top_remove_count{database=\"tartabit\"}[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  },
  {
   "title": "remove execution time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (collection)(rate(mongodb_top_remove_time{database=\"tartabit\"}[1m]))",
     "legendFormat": "{{old_name}}"
    }
   ]
  }
 ]
}