{{ if .Values.grafana }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
type: Opaque
stringData:
  admin-user: "{{ .Values.grafana.user }}"
  admin-password: "{{ .Values.grafana.password }}"
{{ end }}